version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: mock-api-ai-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mock_api_ai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mock-api-ai-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mock_api_ai"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma

volumes:
  db_data:
