version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: mock-api-ai-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mock_api_ai
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app-network-dev

volumes:
  db_data_dev:

networks:
  app-network-dev:
    driver: bridge
